version: '3.1'
services:
  db:
    image: mongo:latest
    container_name: next-todo-app-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    env_file:
      - ./.env.local
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}