version: '3.1'
services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    env_file:
      - .env.local
    links:
      - mongo-db
    networks:
      - mongo-compose-network
    restart: always
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    container_name: mongo
    env_file:
      - .env.local
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongo-compose-network


networks:
    mongo-compose-network:
      driver: bridge

volumes:
  mongodb_data_container: